### ISSUE TITLE
关于UIManagerBase中managedWindowId的问题

### ISSUE THREAD

**Issue by woshihuo12** [tinyantstudio/UIFrameWork#2]
managedWindowId此值为int，看代码是用来控制 uimanager所能管理的 界面的掩码，那么一个manager岂不是只能管理32个界面？就算int是64位，那也感觉不够用啊，限制很大。这是否存在问题?

**Comment by tinyantstudio** [comment]
的确是有这样的问题，如果管理的窗口数量较多可以直接用list来做

**Comment by woshihuo12** [comment]
嗯。。不知道楼主有没有研究 ugui，已经 unity关于lua绑定相关的问题。。

**Comment by tinyantstudio** [comment]
Lua目前还没有加入

**Comment by woshihuo12** [comment]
UGUI 楼主有类似的框架开源么？有这样的打算么？

**Comment by tinyantstudio** [comment]
继续添加一些常用的UI内容，然后制作一个UGUI版本

**Comment by woshihuo12** [comment]
https://github.com/topameng/tolua  这是一个 unity的lua库感觉还不错，我想可以ResourceManager.LoadUIPerfab 类似这样的接口全部导入到lua里面，那样就可以用lua来实现一个纯lua的ui框架，那么游戏就可以支持部分逻辑热更新了，最起码所有ui逻辑可以做到热更。

**Comment by tinyantstudio** [comment]
Cool~
