### ISSUE TITLE
针对现阶段的框架设计的一些思考之网络消息，数据更新，MVC模式

### ISSUE THREAD

**Issue by frideal** [tinyantstudio/UIFrameWork#3]
目前界面的控制和更新，还没有严格意义上使用MVC模式，只有通过UIManager获得相应的界面Window进行刷新Refresh操作或者再打开对应界面的时候传入UpdateData

界面和数据的分离还需要整理下，目前的设想的几个方案如下：

**分而治之：**
1. 针对每个界面做一个Logic逻辑管理，将该界面所需的data，放到对应的Logic中，比如RankLogic+UIRankPanel，RankLogic作为Rank业务的逻辑处理和数据存放处和网络请求消息发放处，比如玩家点击了RankPanel中查看玩家详情的Request，所有的Rank相关的request放到Logic中，发送，同事监听，**网络更新消息到来**，刷新Logic中保存的Data，然后从Logic推送更新界面消息，RankPanel接收到更新消息，从Logic获取数据进行更新，RankPanel中引用Logic

这个算是将MVC中的MC结合成了Logic，因为Logic中放置了数据和一些处理逻辑，监听网络消息，发送更新界面消息（更新界面可以直接调用Window的接口，当然也可以使用事件系统，发送更新事件，个人比较推荐**事件系统**）

分散化的MVC模式，每个业务界面都会有一个Logic和一个WindowPanel，细分的MVC模式

利：
1. 将request和data分开，每个界面维护自己的logic，容易维护
2. 模块开发，每个开发者只关注自己的内容即可

弊：
1. 代码工作量多（这个应该不算吧...）
......

**中央集权**
1. 本地维护一个中央集权的DataManager，这个DataManager代表网络数据，不是ConfigDataManager，一个大的Manager负责整个游戏的数据更新监听工作
2. 本地维护一个RequestManager，所有的请求都通过该Manager进行发送，包括该Request的参数等
3. DataManager监听网络返回消息，数据发送更新，直接抛出客户端更新事件，因为每个界面都会用关心自己的感兴趣的数据消息

整体性的MVC模式

继续思考~

**Comment by FDKPIBC** [comment]
类似三层中逻辑层与数据层的交互？

**Comment by frideal** [comment]
恩，合并了~
