### ISSUE TITLE
目前我感觉此框架中的最大问题

### ISSUE THREAD

**Issue by woshihuo12** [tinyantstudio/UIFrameWork#6]
纵观框架及其使用例子，发现界面的切换全是依靠 hide 隐藏来进行的，而没有相应的很好的 close机制，唯一一个销毁机制在 UIManager的 ClearAllWindow接口。 所以随着界面打开的增多，界面的gameobject都是在加载、隐藏，而没有销毁。感觉是有问题的。比如界面切换，大可把前一界面Clear掉，然后加载当前界面。

**Comment by frideal** [comment]
这个可以添加一个销毁的机制，增加一个可选择性，隐藏或者直接删除。
再切换场景的时候，可以全部删除掉.

**Comment by frideal** [comment]
因为这个框架目前没有加入“Logic+model”，导致了要隐藏界面保证数据的有效性，最近再设计Logic+model进来，保证被删除的时候，数据和逻辑能够正常执行。这个可选择性还是应该交给使用者，应该提供一个接口，我们现在的做法是没关闭一个界面，直接的删除
